version: '3.8'
services:
  task-generator:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./task-generator"]
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "15672:15672"
      - "5672:5672"